# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e586d6953c294c4497434e30f2ee215d69278c577bbd2916dbe3182eccc674a98d48ed85eaf205d183e0ba511327464925c170a913249f792b797f9a1afea871

test:
  secret_key_base: ad34916137c5bb643152497a09adee39decf80a516eadec04edbeaf20bb349e4790b8ca35d1aaac71763a01e276acffdaffe3b4bb992dac8cfa34dea2e6ab0b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
